BOARD_WIDTH = 12
BOARD_HEIGHT = 14

STARTING_HEALTH = 50
PIE_REWARD = 10
COLLISION_DAMAGE = 5

MATCH_TIME_SECONDS = 120
TICK_RATE = 5

STARTING_SNAKE_LENGTH = 3
MAX_PIES = 1
NORMAL_PIES_BEFORE_POWER_PIE = 5
POWER_DURATION_PIES = 3

DIRECTION_UP = "UP"
DIRECTION_DOWN = "DOWN"
DIRECTION_LEFT = "LEFT"
DIRECTION_RIGHT = "RIGHT"

MATCH_STATUS_WAITING = "WAITING"
MATCH_STATUS_RUNNING = "RUNNING"
MATCH_STATUS_FINISHED = "FINISHED"
MATCH_STATUS_DRAW = "DRAW"